[package]
name = "echor"
version = "0.1.0"
authors = ["Sabry"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.14"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "1.0.7"